FROM python:3.12.4

# Set the working directory in the container
WORKDIR /app

# Copy code files
COPY server.py ./

# Install necessary libraries for the code to run
RUN pip install Flask Flask-RESTful Flask-Cors openai waitress

# Expose port
EXPOSE 5000

# Command to run the backend server
CMD ["python", "./server.py"]