FROM python:3.12.4

# Set the working directory in the container
WORKDIR /app

# Copy code files
COPY . .

# Install necessary libraries for the code to run
RUN pip install -r requirements.txt

# Expose port
EXPOSE 5000

# Command to run the backend server
CMD ["python","-u", "./main.py"]